import Link from "next/link";
import {
  LegalBullet,
  LegalBulletList,
  LegalDocumentLayout,
  LegalEmphasis,
  LegalExternalLink,
  LegalParagraph,
  LegalRelatedLinks,
  LegalSection,
} from "@/components/legal/LegalDocumentLayout";

const DEVELOPER_PAGE_URL: string | null = null;
const CONTACT_EMAIL = "calyx.guru@gmail.com";

export default function TermsOfService() {
  return (
    <LegalDocumentLayout
      title="Terms of Service"
      breadcrumbLabel="Terms of Service"
      lastUpdated="June 16, 2026"
      lead="Terms governing your use of the Calyx Guru mobile application."
      sidebar={<LegalRelatedLinks />}
    >
      <LegalParagraph>
        Welcome to Calyx Guru! Please read these Terms of Service (“Terms”)
        carefully before downloading, installing, or using the Calyx Guru mobile
        application (the “APP”).
      </LegalParagraph>

      <LegalParagraph>
        By downloading or using the APP, you agree to be bound by these Terms.
        If you do not agree to these Terms, do not install or use the APP.
      </LegalParagraph>

      <LegalSection title="Description of Service">
        <LegalParagraph>
          Calyx Guru is a mobile application developed by Calyx Guru
          (“Developer”, “we”, “our”, or “us”) as an individual developer. The APP
          provides casual entertainment features, including cybernetic mascot
          animations, digital element art, and interactive fortune-telling
          simulations.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="Entertainment Disclaimer">
        <LegalEmphasis>FOR ENTERTAINMENT PURPOSES ONLY</LegalEmphasis>
        <LegalParagraph>
          All fortune-telling, reading, predictions, and advice provided by Calyx
          Guru are intended strictly for casual entertainment and novelty
          purposes.
        </LegalParagraph>
        <LegalParagraph>
          The APP does not provide real, accurate, or scientifically validated
          predictions.
        </LegalParagraph>
        <LegalParagraph>
          The outputs should never be used as a substitute for professional
          advice, including but not limited to: medical, legal, or psychological
          counseling.
        </LegalParagraph>
        <LegalParagraph>
          The Developer assumes no responsibility or liability for any actions
          taken by the user based on the content generated by the APP. You use
          this APP entirely at your own risk.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="End-User License Agreement (EULA)">
        <LegalParagraph>
          Subject to your compliance with these Terms, the Developer grants you a
          personal, non-exclusive, non-transferable, revocable, and limited
          license to download, install, and use a copy of the APP on a mobile
          device that you own or control, strictly for your personal,
          non-commercial entertainment use.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="User Conduct and Restrictions">
        <LegalParagraph>You agree that you will not:</LegalParagraph>
        <LegalBulletList>
          <LegalBullet>
            Decompile, reverse engineer, dissemble, or attempt to derive the
            source code of the APP.
          </LegalBullet>
          <LegalBullet>
            Modify, adapt, improve, translate, or create derivative work from the
            APP.
          </LegalBullet>
          <LegalBullet>
            Use the APP for any commercial purpose, venture, or money-making
            endeavor without explicit written consent.
          </LegalBullet>
          <LegalBullet>
            Distribute, rent, sub-license, lease, or lend the APP to any
            third-party outside of official Google Play mechanisms.
          </LegalBullet>
        </LegalBulletList>
      </LegalSection>

      <LegalSection title="Intellectual Property Rights">
        <LegalParagraph>
          All rights, titles, and interests in and to the APP — including but
          not limited to the digital artwork, cyber-cat mascot designs,
          animations, UI layouts, sound effects, source code, and the name “Calyx
          Guru” — are owned exclusively by the Developer. Except for the limited
          license granted in Section 3, no ownership or intellectual property
          rights are transferred to you.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="Privacy and Data Use">
        <LegalParagraph>
          Your privacy is highly important to us. Our collection and use of
          information in connection with the APP are governed by our{" "}
          <Link href="/privacy-policy" className="as_legal_email_link">
            Privacy Policy
          </Link>
          , which is incorporated into these Terms by reference. Please review it
          to understand how data is handled.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title='Limitation of Liability and “As-Is” Warranty'>
        <LegalParagraph>
          The APP is provided to you on an “AS IS” and “AS AVAILABLE” basis,
          with all faults and defects, without warranty of any kind.
        </LegalParagraph>
        <LegalParagraph>
          To the maximum extent permitted under applicable law, the Developer
          expressly disclaims all warranties, whether express, implied, or
          statutory. To the maximum extent permitted by law, the Developer shall
          not be liable for any indirect, incidental, special, consequential,
          or punitive damages arising out of or relating to your use of, or
          inability to use, the APP.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="APP Updates and Modifications">
        <LegalParagraph>
          The Developer reserves the right to modify, suspend, or discontinue,
          temporarily or permanently, the APP or any service to which it
          connects, with or without notice and without liability to you. We may
          also roll out automatic or manual updates to improve functionality,
          stability, or visual assets.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="Termination">
        <LegalParagraph>
          These Terms will remain in effect until terminated by either you or
          the Developer. You may terminate these Terms at any time by deleting
          the APP and all copies from your device. The Developer may terminate
          these Terms at any time without notice if you fail to comply with any
          provision herein.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="Governing Law">
        <LegalParagraph>
          These Terms shall be governed by and construed in accordance with the
          laws of Toronto, Ontario, Canada, without regard to its conflict of
          law provisions.
        </LegalParagraph>
      </LegalSection>

      <LegalSection title="Contact Information">
        <LegalParagraph>
          If you have any questions or concerns regarding these Terms of Service,
          please contact the developer at:
        </LegalParagraph>
        <LegalBulletList>
          <LegalBullet>
            By email:{" "}
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="as_legal_email_link"
            >
              {CONTACT_EMAIL}
            </a>
          </LegalBullet>
          <LegalBullet>
            Developer Page:{" "}
            {DEVELOPER_PAGE_URL ? (
              <LegalExternalLink href={DEVELOPER_PAGE_URL}>
                {DEVELOPER_PAGE_URL}
              </LegalExternalLink>
            ) : (
              "Coming soon"
            )}
          </LegalBullet>
        </LegalBulletList>
      </LegalSection>
    </LegalDocumentLayout>
  );
}
