import { DEVELOPER_PAGE_URL } from "@/constants/links";
import type { ReactNode } from "react";
import { Linking, ScrollView, StyleSheet, Text, View } from "react-native";

function ExternalLink({ href, children }: { href: string; children: string }) {
  return (
    <Text
      style={styles.link}
      onPress={() => {
        void Linking.openURL(href);
      }}
      accessibilityRole="link"
      accessibilityLabel={children}
    >
      {children}
    </Text>
  );
}

function Section({
  title,
  children,
}: {
  title?: string;
  children: ReactNode;
}) {
  return (
    <View style={styles.section}>
      {title ? <Text style={styles.sectionTitle}>{title}</Text> : null}
      {children}
    </View>
  );
}

function Paragraph({ children }: { children: string }) {
  return <Text style={styles.paragraph}>{children}</Text>;
}

function Bullet({ children }: { children: ReactNode }) {
  return (
    <View style={styles.bulletRow}>
      <Text style={styles.bulletMarker}>•</Text>
      <Text style={styles.bulletText}>{children}</Text>
    </View>
  );
}

export function RouteTermsOfService() {
  return (
    <ScrollView
      style={styles.root}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Text style={styles.title}>Terms of Service for Calyx Guru</Text>
      <Text style={styles.updated}>Last updated: June 16, 2026</Text>

      <Paragraph>
        Welcome to Calyx Guru! Please read these Terms of Service (“Terms”)
        carefully before downloading, installing, or using the Calyx Guru mobile
        application (the “APP”).
      </Paragraph>

      <Paragraph>
        By downloading or using the APP, you agree to be bound by these Terms.
        If you do not agree to these Terms, do not install or use the APP.
      </Paragraph>

      <Section title="Description of Service">
        <Paragraph>
          Calyx Guru is a mobile application developed by Calyx Guru
          (“Developer”, “we”, “our”, or “us”) as an individual developer. The APP
          provides casual entertainment features, including cybernetic mascot
          animations, digital element art, and interactive fortune-telling
          simulations.
        </Paragraph>
      </Section>

      <Section title="Entertainment Disclaimer">
        <Text style={styles.emphasis}>FOR ENTERTAINMENT PURPOSES ONLY</Text>
        <Paragraph>
          All fortune-telling, reading, predictions, and advice provided by Calyx
          Guru are intended strictly for casual entertainment and novelty
          purposes.
        </Paragraph>
        <Paragraph>
          The APP does not provide real, accurate, or scientifically validated
          predictions.
        </Paragraph>
        <Paragraph>
          The outputs should never be used as a substitute for professional
          advice, including but not limited to: medical, legal, or psychological
          counseling.
        </Paragraph>
        <Paragraph>
          The Developer assumes no responsibility or liability for any actions
          taken by the user based on the content generated by the APP. You use
          this APP entirely at your own risk.
        </Paragraph>
      </Section>

      <Section title="End-User License Agreement (EULA)">
        <Paragraph>
          Subject to your compliance with these Terms, the Developer grants you a
          personal, non-exclusive, non-transferable, revocable, and limited
          license to download, install, and use a copy of the APP on a mobile
          device that you own or control, strictly for your personal,
          non-commercial entertainment use.
        </Paragraph>
      </Section>

      <Section title="User Conduct and Restrictions">
        <Paragraph>You agree that you will not:</Paragraph>
        <Bullet>
          Decompile, reverse engineer, dissemble, or attempt to derive the
          source code of the APP.
        </Bullet>
        <Bullet>
          Modify, adapt, improve, translate, or create derivative work from the
          APP.
        </Bullet>
        <Bullet>
          Use the APP for any commercial purpose, venture, or money-making
          endeavor without explicit written consent.
        </Bullet>
        <Bullet>
          Distribute, rent, sub-license, lease, or lend the APP to any
          third-party outside of official Google Play mechanisms.
        </Bullet>
      </Section>

      <Section title="Intellectual Property Rights">
        <Paragraph>
          All rights, titles, and interests in and to the APP — including but
          not limited to the digital artwork, cyber-cat mascot designs,
          animations, UI layouts, sound effects, source code, and the name “Calyx
          Guru” — are owned exclusively by the Developer. Except for the limited
          license granted in Section 3, no ownership or intellectual property
          rights are transferred to you.
        </Paragraph>
      </Section>

      <Section title="Privacy and Data Use">
        <Paragraph>
          Your privacy is highly important to us. Our collection and use of
          information in connection with the APP are governed by our Privacy
          Policy, which is incorporated into these Terms by reference. Please
          review it to understand how data is handled.
        </Paragraph>
      </Section>

      <Section title='Limitation of Liability and “As-Is” Warranty'>
        <Paragraph>
          The APP is provided to you on an “AS IS” and “AS AVAILABLE” basis,
          with all faults and defects, without warranty of any kind.
        </Paragraph>
        <Paragraph>
          To the maximum extent permitted under applicable law, the Developer
          expressly disclaims all warranties, whether express, implied, or
          statutory. To the maximum extent permitted by law, the Developer shall
          not be liable for any indirect, incidental, special, consequential,
          or punitive damages arising out of or relating to your use of, or
          inability to use, the APP.
        </Paragraph>
      </Section>

      <Section title="APP Updates and Modifications">
        <Paragraph>
          The Developer reserves the right to modify, suspend, or discontinue,
          temporarily or permanently, the APP or any service to which it
          connects, with or without notice and without liability to you. We may
          also roll out automatic or manual updates to improve functionality,
          stability, or visual assets.
        </Paragraph>
      </Section>

      <Section title="Termination">
        <Paragraph>
          These Terms will remain in effect until terminated by either you or
          the Developer. You may terminate these Terms at any time by deleting
          the APP and all copies from your device. The Developer may terminate
          these Terms at any time without notice if you fail to comply with any
          provision herein.
        </Paragraph>
      </Section>

      <Section title="Governing Law">
        <Paragraph>
          These Terms shall be governed by and construed in accordance with the
          laws of Toronto, Ontario, Canada, without regard to its conflict of
          law provisions.
        </Paragraph>
      </Section>

      <Section title="Contact Information">
        <Paragraph>
          If you have any questions or concerns regarding these Terms of Service,
          please contact the developer at:
        </Paragraph>
        <Bullet>By email: calyx.guru@gmail.com</Bullet>
        <Bullet>
          Developer Page:{" "}
          {DEVELOPER_PAGE_URL ? (
            <ExternalLink href={DEVELOPER_PAGE_URL}>
              {DEVELOPER_PAGE_URL}
            </ExternalLink>
          ) : (
            "Coming soon"
          )}
        </Bullet>
      </Section>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f4f7f8",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 12,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0B3C49",
    marginBottom: 4,
  },
  updated: {
    fontSize: 13,
    fontWeight: "500",
    color: "#5a7a82",
    marginBottom: 8,
  },
  section: {
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0B3C49",
    marginTop: 4,
  },
  emphasis: {
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 22,
    color: "#0B3C49",
  },
  paragraph: {
    fontSize: 15,
    lineHeight: 22,
    color: "#1a3d47",
  },
  bulletRow: {
    flexDirection: "row",
    gap: 8,
    paddingRight: 4,
  },
  bulletMarker: {
    fontSize: 15,
    lineHeight: 22,
    color: "#0B3C49",
  },
  bulletText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: "#1a3d47",
  },
  link: {
    color: "#0B6E8C",
    textDecorationLine: "underline",
  },
});
